name: postgres-master-slave
services:
  postgresql-master:
    image: bitnami/postgresql:latest
    shm_size: '1gb'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
    ports:
      - "5432:5432"
    volumes:
      - ./data/master:/bitnami/postgresql

  postgresql-slave:
    image: bitnami/postgresql:latest
    shm_size: '1gb'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MAX_CONNECTIONS=350
    volumes:
      - ./data/slave1:/bitnami/postgresql

  postgresql-slave2:
    image: bitnami/postgresql:latest
    shm_size: '1gb'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MAX_CONNECTIONS=350
    volumes:
      - ./data/slave2:/bitnami/postgresql

  postgresql-slave3:
    image: bitnami/postgresql:latest
    shm_size: '1gb'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MAX_CONNECTIONS=350
    volumes:
      - ./data/slave3:/bitnami/postgresql

  postgresql-slave4:
    image: bitnami/postgresql:latest
    shm_size: '1gb'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MAX_CONNECTIONS=350
    volumes:
      - ./data/slave4:/bitnami/postgresql

  haproxy:
    image: haproxy:latest
    container_name: haproxy-lb
    depends_on:
      - postgresql-slave
      - postgresql-slave2
      - postgresql-slave3
      - postgresql-slave4
    volumes:
      - .haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "5433:5432"
      - "8404:8404"
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-web
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "9090:80"
    depends_on:
      - postgresql-master
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

  redis:
    image: redis:trixie
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/var/lib/redis
